services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: broker
    ports:
    - 15672:15672
    - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - my-bridge

  policy-api:
    image: 'ruby:3.3'
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    ports: [3000:3000]
    depends_on:
      - rabbitmq
    tty: true
    stdin_open: true
    networks:
      - my-bridge

volumes:
  rubygems:

networks:
  default:
  my-bridge:
    external: true
