services:
  postgres:
    image: 'postgres:lasted'
    ports: [5432:5432]
    environment:
      - POSTGRES_USER: postgres
      - POSGRES_PASSWORD: postgres
      - POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
  policy-service:
    image: 'ruby:3.3'
    ports: [3001:3001]
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    tty: true
